"""Regenerate docs/screenshots/ from the live dashboard.

    python tools/capture_screenshots.py

Starts the Streamlit app once per section with ``OA_ONLY_SECTION`` set, so each
section renders without the tab chrome, then photographs it with headless
Chrome driven over the DevTools Protocol.

Chrome is driven over CDP rather than with ``--screenshot`` because Streamlit
delivers its content over a websocket after load: a plain ``--screenshot``
captures the loading skeleton. Here we poll the DOM until the real content is
present, then capture the full page height.

Requires Google Chrome. The README's screenshots are generated by this script
rather than taken by hand, so they cannot drift from the current UI.
"""

import asyncio
import base64
import json
import os
import shutil
import socket
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

import websockets

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "docs" / "screenshots"
APP_PORT = 8599
CDP_PORT = 9333
# Wide enough that the sidebar and the 1180px content column both sit in flow;
# a narrower viewport pushes the sidebar off-canvas and it gets clipped.
WIDTH = 1600
SCALE = 2

CHROME_CANDIDATES = [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    shutil.which("google-chrome") or "",
    shutil.which("chromium") or "",
]

# section -> output filename
SECTIONS = {
    "overview": "overview.png",
    "training": "training-analysis.png",
    "races": "race-results.png",
    "models": "ml-predictions.png",
}


def find_chrome() -> str:
    for candidate in CHROME_CANDIDATES:
        if candidate and Path(candidate).exists():
            return candidate
    raise SystemExit("Google Chrome not found — install it to regenerate screenshots.")


def wait_for_port(port: int, timeout: float = 90.0) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline:
        with socket.socket() as sock:
            sock.settimeout(1.0)
            if sock.connect_ex(("127.0.0.1", port)) == 0:
                return
        time.sleep(0.4)
    raise SystemExit(f"nothing listening on port {port} after {timeout}s")


class CDP:
    """Minimal DevTools Protocol client."""

    def __init__(self, ws):
        self.ws = ws
        self.msg_id = 0

    async def call(self, method: str, **params):
        self.msg_id += 1
        request_id = self.msg_id
        await self.ws.send(json.dumps({
            "id": request_id, "method": method, "params": params,
        }))
        while True:
            message = json.loads(await self.ws.recv())
            if message.get("id") == request_id:
                if "error" in message:
                    raise RuntimeError(f"{method}: {message['error']}")
                return message.get("result", {})


async def capture_page(url: str, out_path: Path) -> None:
    targets = json.loads(
        urllib.request.urlopen(f"http://127.0.0.1:{CDP_PORT}/json").read()
    )
    page = next(t for t in targets if t["type"] == "page")

    async with websockets.connect(
        page["webSocketDebuggerUrl"], max_size=200 * 1024 * 1024
    ) as ws:
        cdp = CDP(ws)
        await cdp.call("Page.enable")
        await cdp.call(
            "Emulation.setDeviceMetricsOverride",
            width=WIDTH, height=1200, deviceScaleFactor=SCALE, mobile=False,
        )
        await cdp.call("Page.navigate", url=url)

        # Poll until Streamlit has painted real content, not its skeleton.
        deadline = time.time() + 90
        while time.time() < deadline:
            await asyncio.sleep(1.0)
            result = await cdp.call(
                "Runtime.evaluate",
                expression=(
                    "(() => {"
                    "  const app = document.querySelector('.block-container');"
                    "  if (!app) return 0;"
                    "  const charts = document.querySelectorAll('.js-plotly-plot').length;"
                    "  const text = app.innerText.trim().length;"
                    "  return (charts > 0 && text > 200) ? text : 0;"
                    "})()"
                ),
                returnByValue=True,
            )
            if result.get("result", {}).get("value"):
                break
        else:
            raise SystemExit(f"content never rendered for {url}")

        await asyncio.sleep(2.5)  # let chart transitions settle

        # Frame on the main content column. Streamlit positions the sidebar at a
        # small negative x, so including it always clips its left edge; the
        # content column on its own reads as a clean report page.
        box = await cdp.call(
            "Runtime.evaluate",
            expression=(
                "(() => {"
                "  const main = document.querySelector("
                "    '[data-testid=\"stMain\"] .block-container') "
                "    || document.querySelector('.block-container');"
                "  const r = main.getBoundingClientRect();"
                "  return JSON.stringify({"
                "    left: Math.floor(r.left + window.scrollX),"
                "    width: Math.ceil(r.width),"
                "    bottom: Math.ceil(r.bottom + window.scrollY)"
                "  });"
                "})()"
            ),
            returnByValue=True,
        )
        m = json.loads(box["result"]["value"])
        pad = 28
        clip_x = max(0, m["left"] - pad)
        clip_w = m["width"] + pad * 2
        clip_h = m["bottom"] + pad

        # deviceScaleFactor already provides the 2x; a clip scale of 2 on top of
        # it would double-apply and crop the page.
        shot = await cdp.call(
            "Page.captureScreenshot",
            format="png",
            captureBeyondViewport=True,
            clip={"x": clip_x, "y": 0, "width": clip_w, "height": clip_h, "scale": 1},
        )
        out_path.write_bytes(base64.b64decode(shot["data"]))
        _downscale(out_path)


def _downscale(path: Path, target_width: int = 1600) -> None:
    """Shrink a 2x capture to a sensible size for embedding in the README."""
    if shutil.which("sips"):   # macOS, no extra dependency
        subprocess.run(
            ["sips", "--resampleWidth", str(target_width), str(path)],
            check=False, capture_output=True,
        )


def main() -> None:
    chrome = find_chrome()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Capturing {len(SECTIONS)} sections to {OUT_DIR.relative_to(REPO_ROOT)}/")

    browser = subprocess.Popen(
        [
            chrome, "--headless=new", "--disable-gpu", "--hide-scrollbars",
            f"--remote-debugging-port={CDP_PORT}",
            "--remote-allow-origins=*",
            f"--window-size={WIDTH},1200",
            "--no-first-run", "--no-default-browser-check",
            "--user-data-dir=/tmp/oa-screenshot-profile",
            "about:blank",
        ],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    try:
        wait_for_port(CDP_PORT)
        for section, filename in SECTIONS.items():
            env = {**os.environ, "OA_ONLY_SECTION": section}
            server = subprocess.Popen(
                [
                    sys.executable, "-m", "streamlit", "run", "dashboard.py",
                    "--server.port", str(APP_PORT),
                    "--server.headless", "true",
                    "--browser.gatherUsageStats", "false",
                ],
                cwd=REPO_ROOT, env=env,
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
            try:
                wait_for_port(APP_PORT)
                out = OUT_DIR / filename
                asyncio.run(capture_page(f"http://127.0.0.1:{APP_PORT}", out))
                print(f"  {filename}  ({out.stat().st_size // 1024} KB)")
            finally:
                server.terminate()
                server.wait(timeout=20)
                time.sleep(1.0)
    finally:
        browser.terminate()
        browser.wait(timeout=20)
    print("Done.")


if __name__ == "__main__":
    main()
